[package]
name = "csv-viewer"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/SmoothTurtle872/csv-viewer"

[dependencies]
csv = "1.4.0"
iced = "0.14.0"
iced_aw = { version = "0.14.1", default-features = false, features = ["menu"] }
open = "5.4.1"
rand = "0.10.2"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
